# Generated by Django 3.2.13 on 2022-04-22 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_db2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Db2',
        ),
    ]
